### ISSUE TITLE
pin vtk and occt

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD_Conda#10]
vtk is moving too fast, so let's pin it to 8.1
+pin occt, as we have removed the track-feature.

**Comment by luzpaz** [comment]
VTK 8.1.0 shows so warnings: http://freecadweb.org/tracker/view.php?id=3852

**Comment by looooo** [comment]
We already arrived at vtk 8.2.0 and i think this warning is related to the vtk version and not to conda.
