### ISSUE TITLE
OpenSCADUtils.py needs syntax edits to be used with Python3.

### ISSUE THREAD

**Issue by Lordling** [FreeCAD/FreeCAD_Conda#16]
So we managed to sew FreeCAD and its related dependencies into our environment and got it working with Python3 (OS Ubuntu 18.04, Bionic Beaver). However, I had to manually edit and update OpenSCADUtils.py in a few places in order to use the mesh difference function without crashing. 

Namely, a couple of generator objects [g] still use the Python2 g.next() syntax instead of the Python3 next(g). Specifically for the OpenSCADUtils meshoptempfile functions, I had to make the following two changes to make my code useable (line numbers included in images):

![screenshot from 2018-07-10 02-14-48](https://user-images.githubusercontent.com/6563220/42504222-b1b80092-8458-11e8-9bba-f3241f7e08cf.png)
![screenshot from 2018-07-10 02-13-46](https://user-images.githubusercontent.com/6563220/42504223-b1f3add6-8458-11e8-82a3-d47d576c02b2.png)

The changes are relatively minor but it's something that we can't track in our repo itself, FreeCAD being an external library and all. Would it be possible to get an updated OpenSCADUtils.py officially supported for the purpose of using meshoptempfile in Python3 applications?

**Comment by looooo** [comment]
thanks for reporting. PR is on it's way. If you find any other problems please report them to https://forum.freecadweb.org/viewtopic.php?f=10&t=12534&start=660 or if possible create a PR for freecad directly.

**Comment by looooo** [comment]
@Lordling have you tested this in a recent version of FreeCAD. I guess it should be fixed. If so please close the issue.
