### ISSUE TITLE
Add GraphViz

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD_Conda#21]
https://github.com/conda-forge/graphviz-feedstock
It's used to build the [Dependency Graph](https://www.freecadweb.org/wiki/Std_DependencyGraph)

**Comment by looooo** [comment]
https://github.com/FreeCAD/FreeCAD_Conda/commit/17b3f498cd685b84a171c183d8c5a6cba6873289

Is graphviz installed in the appimage?

**Comment by looooo** [comment]
Same for me. Lets try it:
https://github.com/FreeCAD/FreeCAD-AppImage/pull/11
