### ISSUE TITLE
libstlvis.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joe-92** [FreeCAD/FreeCAD_Conda#24]
After reinstalling FreeCAD I get the following error when opening a document:

`libstlvis.so: cannot open shared object file: No such file or directory`

Is this bug already known?

**Comment by joe-92** [comment]
I've figured out the problem: The newest netgen package (6.2.1808) on conda-forge seems to be broken, if I downgrade to version 6.2.1804 everything works as expected.

**Comment by looooo** [comment]
can you share your environment?
`conda list`
