### ISSUE TITLE
bump occt to 7.5.1

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD_Conda#41]
https://anaconda.org/conda-forge/occt
7.5.1 adds error checking that 7.4.0 is missing and makes FC hang
Thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=55523&p=477790#p477783

**Comment by luzpaz** [comment]
ping @looooo @sgrogan

**Comment by looooo** [comment]
I still would like to go to vtk9 first. And do the occt 7.5 migration later.

**Comment by gbroques** [comment]
This is also important and desirable for `.gltf` export:
https://forum.freecadweb.org/viewtopic.php?f=8&t=31680&p=450917&#p450658

See Also:
https://www.khronos.org/gltf/

**Comment by looooo** [comment]
@luzpaz @gbroques we are only waiting for gmsh to be updated to occt7.5:
https://github.com/conda-forge/gmsh-feedstock/pull/39
https://forum.freecadweb.org/viewtopic.php?f=42&t=56963&p=490073#p490073

**Comment by luzpaz** [comment]
![Screenshot_20230131_204811](https://user-images.githubusercontent.com/4140247/215925099-31133abb-eb52-4abd-ab06-5425549653d2.png)

This ticket can be closed.
